---
workspace:
  base: /workspace
  path: mossbot

pipeline:
  test:
    image: xsteadfastx/tox-python:latest
    commands:
      - echo $PWD
      - tox -e ${TOXENV}

matrix:
  TOXENV:
    - py36
    - flake8
    - pylint
    - mypy
