---
workspace:
  base: /workspace
  path: mossbot

pipeline:

  test-py36:
    image: xsteadfastx/tox-python:latest
    commands:
      - tox -e py36

  test-flake8:
    image: xsteadfastx/tox-python:latest
    commands:
      - tox -e flake8

  test-pylint:
    image: xsteadfastx/tox-python:latest
    commands:
      - tox -e pylint

  test-mypy:
    image: xsteadfastx/tox-python:latest
    commands:
      - tox -e mypy

  build:
    image: docker
    commands:
      - apk add --no-cache make
      - make build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: yes
    when:
      branch: master

  deploy:
    image: docker
    commands:
      - apk add --no-cache python3
      - pip3 install docker
      - pip3 install tinydb
      - python3 deploy.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mossbot:/opt/mossbot
    privileged: yes
    when:
      branch: master
