---
workspace:
  base: /workspace
  path: mossbot

pipeline:

  test:
    image: xsteadfastx/tox-python:latest
    commands:
      - echo $PWD
      - tox -e ${TOXENV}

  build:
    image: docker
    commands:
      - docker build -t mossbot .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: yes

matrix:
  TOXENV:
    - py36
    - flake8
    - pylint
    - mypy
